version: '3.9'

volumes:
    data_postgres:


services:
  postgres:
    container_name: postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/data/postgres"
    volumes:
       - data_postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped