CREATE TABLE "CPC" (
  "ID_CPC" SERIAL PRIMARY KEY,
  "CODIGO_IES" bigint,
  "CODIGO_CURSO" bigint,
  "CPC_CONTINUO" float,
  "CPC_FAIXA" int
);

CREATE TABLE "IGC" (
  "ID_IGC" SERIAL PRIMARY KEY,
  "CODIGO_IES" bigint,
  "SIGLA_IES" varchar,
  "IGC_CONTINUO" float,
  "IGC_FAIXA" varchar
);

CREATE TABLE "ENADE" (
  "ID_ENADE" SERIAL PRIMARY KEY,
  "CODIGO_IES" bigint,
  "NOME_IES" varchar,
  "CODIGO_CURSO" bigint,
  "MODALIDADE_ENSINO" varchar,
  "CONCEITO_ENADE_CONTINUO" float,
  "CONCEITO_ENADE_FAIXA" varchar
);

CREATE TABLE "CENSO_IES" (
  "ID_CENSO_IES" SERIAL PRIMARY KEY,
  "NO_REGIAO_IES" varchar,
  "CO_REGIAO_IES" int,
  "NO_UF_IES" varchar,
  "SG_UF_IES" varchar,
  "CO_UF_IES" int,
  "NO_MUNICIPIO_IES" varchar,
  "CO_MUNICIPIO_IES" bigint,
  "TP_ORGANIZACAO_ACADEMICA" int,
  "TP_CATEGORIA_ADMINISTRATIVA" int,
  "CO_IES" bigint,
  "NO_IES" varchar,
  "SG_IES" varchar,
  "QT_DOCENTE_TOTAL" int,
  "QT_DOCENTE_EXE" int,
  "DOC_EX_FEMI" int,
  "DOC_EX_MASC" int,
  "DOC_EX_SEM_GRAD" int,
  "DOC_EX_GRAD" int,
  "DOC_EX_ESP" int,
  "DOC_EX_MEST" int,
  "DOC_EX_DOUT" int,
  "IN_ACESSO_PORTAL_CAPES" int,
  "IN_ACESSO_OUTRAS_BASES" int,
  "IN_ASSINA_OUTRA_BASE" int,
  "IN_REPOSITORIO_INSTITUCIONAL" int,
  "IN_BUSCA_INTEGRADA" int,
  "IN_SERVICO_INTERNET" int,
  "IN_PARTICIPA_REDE_SOCIAL" int,
  "IN_CATALOGO_ONLINE" int
);

CREATE TABLE "CENSO_CURSO" (
  "ID_CENSO_CURSO" SERIAL PRIMARY KEY,
  "CO_IES" bigint,
  "NO_CINE_ROTULO" varchar,
  "CO_CINE_ROTULO" varchar,
  "CO_CINE_AREA_GERAL" varchar,
  "NO_CINE_AREA_GERAL" varchar,
  "CO_CINE_AREA_ESPECIFICA" varchar,
  "NO_CINE_AREA_ESPECIFICA" varchar,
  "CO_CINE_AREA_DETALHADA" varchar,
  "NO_CINE_AREA_DETALHADA" varchar,
  "TP_GRAU_ACADEMICO" int,
  "TP_MODALIDADE_ENSINO" int,
  "QT_VAGA_TOTAL" bigint,
  "QT_VAGA_TOTAL_DIURNO" bigint,
  "QT_VAGA_TOTAL_NOTURNO" bigint,
  "QT_VAGA_TOTAL_EAD" bigint,
  "QT_MAT" bigint,
  "QT_CONC" bigint
);
