# Generated by Django 4.0.3 on 2022-04-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCpcmodel',
            fields=[
                ('id_cpc', models.AutoField(db_column='ID_CPC', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_cpcmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiCursomodel',
            fields=[
                ('id_censo_curso', models.AutoField(db_column='ID_CENSO_CURSO', primary_key=True, serialize=False)),
                ('no_cine_rotulo', models.CharField(db_column='NO_CINE_ROTULO', max_length=100)),
                ('co_cine_rotulo', models.CharField(db_column='CO_CINE_ROTULO', max_length=100)),
                ('co_cine_area_geral', models.CharField(db_column='CO_CINE_AREA_GERAL', max_length=100)),
                ('no_cine_area_geral', models.CharField(db_column='NO_CINE_AREA_GERAL', max_length=100)),
                ('co_cine_area_especifica', models.CharField(db_column='CO_CINE_AREA_ESPECIFICA', max_length=100)),
                ('no_cine_area_especifica', models.CharField(db_column='NO_CINE_AREA_ESPECIFICA', max_length=100)),
                ('co_cine_area_detalhada', models.CharField(db_column='CO_CINE_AREA_DETALHADA', max_length=100)),
                ('no_cine_area_detalhada', models.CharField(db_column='NO_CINE_AREA_DETALHADA', max_length=100)),
            ],
            options={
                'db_table': 'api_cursomodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiEnademodel',
            fields=[
                ('id_enade', models.AutoField(db_column='ID_ENADE', primary_key=True, serialize=False)),
                ('nome_ies', models.CharField(db_column='NOME_IES', max_length=100)),
                ('modalidade_ensino', models.CharField(db_column='MODALIDADE_ENSINO', max_length=100)),
                ('conceito_enade_faixa', models.CharField(db_column='CONCEITO_ENADE_FAIXA', max_length=100)),
            ],
            options={
                'db_table': 'api_enademodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiIesmodel',
            fields=[
                ('id_censo_ies', models.AutoField(db_column='ID_CENSO_IES', primary_key=True, serialize=False)),
                ('no_regiao_ies', models.CharField(db_column='NO_REGIAO_IES', max_length=100)),
                ('no_uf_ies', models.CharField(db_column='NO_UF_IES', max_length=100)),
                ('sg_uf_ies', models.CharField(db_column='SG_UF_IES', max_length=100)),
                ('no_municipio_ies', models.CharField(db_column='NO_MUNICIPIO_IES', max_length=100)),
                ('no_ies', models.CharField(db_column='NO_IES', max_length=100)),
                ('sg_ies', models.CharField(db_column='SG_IES', max_length=100)),
            ],
            options={
                'db_table': 'api_iesmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiIgcmodel',
            fields=[
                ('id_igc', models.AutoField(db_column='ID_IGC', primary_key=True, serialize=False)),
                ('sigla_ies', models.CharField(db_column='SIGLA_IES', max_length=100)),
                ('igc_faixa', models.CharField(db_column='IGC_FAIXA', max_length=100)),
            ],
            options={
                'db_table': 'api_igcmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensoCurso',
            fields=[
                ('id_censo_curso', models.AutoField(db_column='ID_CENSO_CURSO', primary_key=True, serialize=False)),
                ('co_ies', models.BigIntegerField(blank=True, db_column='CO_IES')),
                ('no_cine_rotulo', models.CharField(blank=True, db_column='NO_CINE_ROTULO', max_length=255)),
                ('co_cine_rotulo', models.CharField(blank=True, db_column='CO_CINE_ROTULO', max_length=255)),
                ('co_cine_area_geral', models.CharField(blank=True, db_column='CO_CINE_AREA_GERAL', max_length=255)),
                ('no_cine_area_geral', models.CharField(blank=True, db_column='NO_CINE_AREA_GERAL', max_length=255)),
                ('co_cine_area_especifica', models.CharField(blank=True, db_column='CO_CINE_AREA_ESPECIFICA', max_length=255)),
                ('no_cine_area_especifica', models.CharField(blank=True, db_column='NO_CINE_AREA_ESPECIFICA', max_length=255)),
                ('co_cine_area_detalhada', models.CharField(blank=True, db_column='CO_CINE_AREA_DETALHADA', max_length=255)),
                ('no_cine_area_detalhada', models.CharField(blank=True, db_column='NO_CINE_AREA_DETALHADA', max_length=255)),
                ('tp_grau_academico', models.IntegerField(blank=True, db_column='TP_GRAU_ACADEMICO')),
                ('tp_modalidade_ensino', models.IntegerField(blank=True, db_column='TP_MODALIDADE_ENSINO')),
                ('qt_vaga_total', models.BigIntegerField(blank=True, db_column='QT_VAGA_TOTAL')),
                ('qt_vaga_total_diurno', models.BigIntegerField(blank=True, db_column='QT_VAGA_TOTAL_DIURNO')),
                ('qt_vaga_total_noturno', models.BigIntegerField(blank=True, db_column='QT_VAGA_TOTAL_NOTURNO')),
                ('qt_vaga_total_ead', models.BigIntegerField(blank=True, db_column='QT_VAGA_TOTAL_EAD')),
                ('qt_mat', models.BigIntegerField(blank=True, db_column='QT_MAT')),
                ('qt_conc', models.BigIntegerField(blank=True, db_column='QT_CONC')),
            ],
            options={
                'db_table': 'CENSO_CURSO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpc',
            fields=[
                ('id_cpc', models.AutoField(db_column='ID_CPC', primary_key=True, serialize=False)),
                ('codigo_ies', models.BigIntegerField(blank=True, db_column='CODIGO_IES')),
                ('codigo_curso', models.BigIntegerField(blank=True, db_column='CODIGO_CURSO')),
                ('cpc_continuo', models.TextField(blank=True, db_column='CPC_CONTINUO')),
                ('cpc_faixa', models.IntegerField(blank=True, db_column='CPC_FAIXA')),
            ],
            options={
                'db_table': 'CPC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enade',
            fields=[
                ('id_enade', models.AutoField(db_column='ID_ENADE', primary_key=True, serialize=False)),
                ('codigo_ies', models.BigIntegerField(blank=True, db_column='CODIGO_IES')),
                ('nome_ies', models.CharField(blank=True, db_column='NOME_IES', max_length=255)),
                ('codigo_curso', models.BigIntegerField(blank=True, db_column='CODIGO_CURSO')),
                ('modalidade_ensino', models.CharField(blank=True, db_column='MODALIDADE_ENSINO', max_length=255)),
                ('conceito_enade_continuo', models.TextField(blank=True, db_column='CONCEITO_ENADE_CONTINUO')),
                ('conceito_enade_faixa', models.CharField(blank=True, db_column='CONCEITO_ENADE_FAIXA', max_length=255)),
            ],
            options={
                'db_table': 'ENADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Igc',
            fields=[
                ('id_igc', models.AutoField(db_column='ID_IGC', primary_key=True, serialize=False)),
                ('codigo_ies', models.BigIntegerField(blank=True, db_column='CODIGO_IES')),
                ('sigla_ies', models.CharField(blank=True, db_column='SIGLA_IES', max_length=255)),
                ('igc_continuo', models.TextField(blank=True, db_column='IGC_CONTINUO')),
                ('igc_faixa', models.CharField(blank=True, db_column='IGC_FAIXA', max_length=255)),
            ],
            options={
                'db_table': 'IGC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensoIes',
            fields=[
                ('id_censo_ies', models.AutoField(db_column='ID_CENSO_IES', primary_key=True, serialize=False)),
                ('no_regiao_ies', models.CharField(blank=True, db_column='NO_REGIAO_IES', max_length=255)),
                ('co_regiao_ies', models.IntegerField(blank=True, db_column='CO_REGIAO_IES')),
                ('no_uf_ies', models.CharField(blank=True, db_column='NO_UF_IES', max_length=255)),
                ('sg_uf_ies', models.CharField(blank=True, db_column='SG_UF_IES', max_length=255)),
                ('co_uf_ies', models.IntegerField(blank=True, db_column='CO_UF_IES')),
                ('no_municipio_ies', models.CharField(blank=True, db_column='NO_MUNICIPIO_IES', max_length=255)),
                ('co_municipio_ies', models.BigIntegerField(blank=True, db_column='CO_MUNICIPIO_IES')),
                ('tp_organizacao_academica', models.IntegerField(blank=True, db_column='TP_ORGANIZACAO_ACADEMICA')),
                ('tp_categoria_administrativa', models.IntegerField(blank=True, db_column='TP_CATEGORIA_ADMINISTRATIVA')),
                ('co_ies', models.BigIntegerField(blank=True, db_column='CO_IES')),
                ('no_ies', models.CharField(blank=True, db_column='NO_IES', max_length=255)),
                ('sg_ies', models.CharField(blank=True, db_column='SG_IES', max_length=255)),
                ('qt_docente_total', models.IntegerField(blank=True, db_column='QT_DOCENTE_TOTAL')),
                ('qt_docente_exe', models.IntegerField(blank=True, db_column='QT_DOCENTE_EXE')),
                ('doc_ex_femi', models.IntegerField(blank=True, db_column='DOC_EX_FEMI')),
                ('doc_ex_masc', models.IntegerField(blank=True, db_column='DOC_EX_MASC')),
                ('doc_ex_sem_grad', models.IntegerField(blank=True, db_column='DOC_EX_SEM_GRAD')),
                ('doc_ex_grad', models.IntegerField(blank=True, db_column='DOC_EX_GRAD')),
                ('doc_ex_esp', models.IntegerField(blank=True, db_column='DOC_EX_ESP')),
                ('doc_ex_mest', models.IntegerField(blank=True, db_column='DOC_EX_MEST')),
                ('doc_ex_dout', models.IntegerField(blank=True, db_column='DOC_EX_DOUT')),
                ('in_acesso_portal_capes', models.IntegerField(blank=True, db_column='IN_ACESSO_PORTAL_CAPES')),
                ('in_acesso_outras_bases', models.IntegerField(blank=True, db_column='IN_ACESSO_OUTRAS_BASES')),
                ('in_assina_outra_base', models.IntegerField(blank=True, db_column='IN_ASSINA_OUTRA_BASE')),
                ('in_repositorio_institucional', models.IntegerField(blank=True, db_column='IN_REPOSITORIO_INSTITUCIONAL')),
                ('in_busca_integrada', models.IntegerField(blank=True, db_column='IN_BUSCA_INTEGRADA')),
                ('in_servico_internet', models.IntegerField(blank=True, db_column='IN_SERVICO_INTERNET')),
                ('in_participa_rede_social', models.IntegerField(blank=True, db_column='IN_PARTICIPA_REDE_SOCIAL')),
                ('in_catalogo_online', models.IntegerField(blank=True, db_column='IN_CATALOGO_ONLINE')),
            ],
            options={
                'db_table': 'CENSO_IES',
            },
        ),
    ]
