# Generated by Django 4.0.3 on 2022-04-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpcmodel',
            fields=[
                ('ID_CPC', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='igcmodel',
            fields=[
                ('ID_IGC', models.IntegerField(primary_key=True, serialize=False)),
                ('SIGLA_IES', models.CharField(max_length=100)),
                ('IGC_FAIXA', models.CharField(max_length=100)),
            ],
        ),
    ]
