# Generated by Django 4.0.3 on 2022-04-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursomodel',
            fields=[
                ('ID_CENSO_CURSO', models.IntegerField(primary_key=True, serialize=False)),
                ('NO_CINE_ROTULO', models.CharField(max_length=100)),
                ('CO_CINE_ROTULO', models.CharField(max_length=100)),
                ('CO_CINE_AREA_GERAL', models.CharField(max_length=100)),
                ('NO_CINE_AREA_GERAL', models.CharField(max_length=100)),
                ('CO_CINE_AREA_ESPECIFICA', models.CharField(max_length=100)),
                ('NO_CINE_AREA_ESPECIFICA', models.CharField(max_length=100)),
                ('CO_CINE_AREA_DETALHADA', models.CharField(max_length=100)),
                ('NO_CINE_AREA_DETALHADA', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='enademodel',
            fields=[
                ('ID_ENADE', models.IntegerField(primary_key=True, serialize=False)),
                ('NOME_IES', models.CharField(max_length=100)),
                ('MODALIDADE_ENSINO', models.CharField(max_length=100)),
                ('CONCEITO_ENADE_FAIXA', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='iesmodel',
            fields=[
                ('ID_CENSO_IES', models.IntegerField(primary_key=True, serialize=False)),
                ('NO_REGIAO_IES', models.CharField(max_length=100)),
                ('NO_UF_IES', models.CharField(max_length=100)),
                ('SG_UF_IES', models.CharField(max_length=100)),
                ('NO_MUNICIPIO_IES', models.CharField(max_length=100)),
                ('NO_IES', models.CharField(max_length=100)),
                ('SG_IES', models.CharField(max_length=100)),
            ],
        ),
    ]
